# .github/workflows/deploy-pipeline.yml

name: PipelineGustavo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

       - name: Start server in background
        run: |
          python app.py

  test: 
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run tests
        run: |
          python teste_app.py
  deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: DEPLOY RENDER GUSTAVO
          env:
            RENDER_API_KEY: ${{ secrets.KEY_RENDER_GUSTAVO }}
            RENDER_SERVICE_ID: ${{ secrets.ID_RENDER_GUSTAVO }}
          run: |
            curl -X POST https://api.render.com/deploy/sync \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -H "Content-Type: application/json" \
              -d '{"serviceId": "'"$RENDER_SERVICE_ID"'"}'