# .github/workflows/deploy-pipeline.yml

name: PipelineGustavo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Buildando Imagem Docker
        run: |
          docker build -t meuapp .

      - name: Rodando Container
        run: |
          docker run meuapp:latest echo "Container Rodou!"

  test: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Iniciar aplicação com Docker Compose
        run: |
          docker-compose up -d

      - name: Parar containers
        run: |
          docker-compose run api python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY RENDER GUSTAVO
        env:
          RENDER_API_KEY: ${{ secrets.KEY_RENDER_GUSTAVO }}
          RENDER_SERVICE_ID: ${{ secrets.ID_RENDER_GUSTAVO }}
        run: |
          curl -X POST https://api.render.com/deploy/sync \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "'"$RENDER_SERVICE_ID"'"}'