# .github/workflows/deploy-pipeline.yml

name: PipelineGustavo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Buildando Imagem Docker
        run: |
          docker build -t meuapp .

      - name: Rodando Container
        run: |
          docker run meuapp:latest echo "Container Rodou!"

  test: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalando Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version 

      - name: Rodar o Compose
        run: |
          docker-compose run api python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY RENDER GUSTAVO
        env:
          RENDER_API_KEY: ${{ secrets.KEY_RENDER_GUSTAVO }}
          RENDER_SERVICE_ID: ${{ secrets.ID_RENDER_GUSTAVO }}
        run: |
          curl --request POST \
               --url https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
               --header 'accept: application/json' \
               --header 'Authorization: Bearer $RENDER_API_KEY' \
               --header 'content-type: application/json' \
               --data '  {"clearCache": "do_not_clear"}'