# .github/workflows/deploy-pipeline.yml

name: PipelineGustavo

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubunto-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar servidor e testes
        run: |
          python app.py &  # inicia o servidor em background
          sleep 5          # espera o servidor subir
          pytest teste_app.py
    
